<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MessageQueueNET</RootNamespace>
    <AssemblyName>MessageQueueNET</AssemblyName>
	<LangVersion>12</LangVersion>
	<Nullable>enable</Nullable>  
    <UserSecretsId>dac92db3-dbf3-47e8-81ec-7f3e54481482</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\linux-x64.pubxml" />
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\win-x64.pubxml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aspire\MessageQueueNET.ServiceDefaults\MessageQueueNET.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\shared\MessageQueueNET.Client\MessageQueueNET.Client.csproj" />
  </ItemGroup>

</Project>
